### PR TITLE
Fix #3401 trailing ,,,, in molecular alterations

### LINKED ISSUE #3401: cancer type summary tab issue
https://cbioportal.mskcc.org/beta/index.do?session_id=5a12f277498eb8b3d5605cce

image

It is working on the currently production site:

https://cbioportal.mskcc.org/index.do?session_id=596d398f498e5df2e292a24b

[update] not working on production either. Need to debug the api.

### PR DESCRIPTION
**Pull request by inodb**
Fix #3401. When values field of molecular alteration has trailing empty ,,, the value is
not converted to an empty string in the array. This solves that issue by always
returning an empty string. However we are still not handling these empty values
in a specific way on cancer type summary page.

### CODE REVIEW

File: persistence/persistence-mybatis/src/test/java/org/cbioportal/persistence/mybatis/MolecularDataMyBatisRepositoryTest.java [hunk 1]
```diff
@@ -44,12 +44,12 @@ public void getGeneMolecularAlterations() throws Exception {
         GeneMolecularAlteration molecularAlteration1 = result.get(0);
         Assert.assertEquals((Integer) 207, molecularAlteration1.getEntrezGeneId());
         String[] expected = {"-0.4674","-0.6270","-1.2266","-1.2479","-1.2262","0.6962","-0.3338","-0.1264","0.7559","-1.1267","-0.5893",
-        "-1.1546","-1.0027","-1.3157"};
+        "-1.1546","-1.0027","-1.3157",""};
```
Comment (inodb) [inline persistence/persistence-mybatis/src/test/java/org/cbioportal/persistence/mybatis/MolecularDataMyBatisRepositoryTest.java]: This is kinda weird but it seems that the imported testSQL has a trailing `,` for all these datasets

File: model/src/main/java/org/cbioportal/model/MolecularAlteration.java [hunk 2]
```diff
@@ -24,9 +24,11 @@ public void setValues(String values) {
...
      */
     public String[] getSplitValues() {
-    	if (splitValues == null) {
-    		splitValues = values.split(",");
-    	}
-    	return splitValues;
+        if (splitValues == null) {
+            // Use Integer.MIN_VALUE to return empty string for empty when
+            // trailing ,,,,
+            splitValues = values.split(",", Integer.MIN_VALUE);
```
Comment (jjgao) [inline model/src/main/java/org/cbioportal/model/MolecularAlteration.java]: just nitpicking: -1 might be enough :)
