### PR TITLE
Make the "fetchGenericAssayData()" method more robust against possible NPEs

### LINKED ISSUE #10877: NullPointerException: Cannot invoke "java.util.Map.get(Object)" because the return value of "java.util.Map.get(Object)"...
Sentry Issue: [CBIOPORTAL-BACKEND-FNR](https://memorial-sloan-kettering.sentry.io/issues/5563909166/?referrer=github_integration)

```
NullPointerException: Cannot invoke "java.util.Map.get(Object)" because the return value of "java.util.Map.get(Object)" is null
    at org.cbioportal.service.impl.GenericAssayServiceImpl.fetchGenericAssayData(GenericAssayServiceImpl.java:162)
    at org.cbioportal.service.impl.StudyViewServiceImpl.lambda$fetchGenericAssayDataCounts$15(StudyViewServiceImpl.java:429)
    at org.cbioportal.service.impl.StudyViewServiceImpl.fetchGenericAssayDataCounts(StudyViewServiceImpl.java:433)
    at org.cbioportal.web.StudyViewController.fetchGenericAssayDataCounts(StudyViewController.java:1021)
    at org.cbioportal.web.StudyViewController$$SpringCGLIB$$0.fetchGenericAssayDataCounts(<generated>)
...
(95 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by KingAlex1985**
Make the "fetchGenericAssayData()" method more robust against possible NullPointerExceptions

Fix #10877

Describe changes proposed in this pull request:
- Added NullPointer checks
- In case of NPE an IllegalArgumentException will be thrown

# Checks
- [x] The commit log is comprehensible. It follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). We can fix this during merge by using a squash+merge if necessary
- [x] Has tests or has a separate issue that describes the types of test that should be created. If no test is included it should explicitly be mentioned in the PR why there is no test.
- [ ] Is this PR adding logic based on one or more **clinical** attributes? If yes, please make sure validation for this attribute is also present in the data validation / data loading layers (in backend repo) and documented in [File-Formats Clinical data section](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#clinical-data)!
- [ ] Make sure your PR has one of the labels defined in https://github.com/cBioPortal/cbioportal/blob/master/.github/release-drafter.yml

### CODE REVIEW

**Review by inodb — APPROVED** [review]
LGTM - thank you

**Comment by KingAlex1985** [comment]
Hi @dippindots
Can you please review this PR.
Thank you in advance.

Greetings,
Alex

File: src/main/java/org/cbioportal/legacy/service/impl/GenericAssayServiceImpl.java [hunk 1]
```diff
@@ -157,8 +166,18 @@ public List<GenericAssayData> fetchGenericAssayData(List<String> molecularProfil
...
+            if (studyMolecularProfiles == null) {
+                throw new IllegalArgumentException("MolecularProfiles for StudyId " + sample.getCancerStudyIdentifier() + " is null.");
+            }
+            for (MolecularProfile molecularProfile : studyMolecularProfiles) {
                 String molecularProfileId = molecularProfile.getStableId();
+                if (internalSampleIdsMap.get(molecularProfileId) == null) {
+                    throw new IllegalArgumentException("InternalSampleIdsMap for MolecularProfileId " + molecularProfileId + " is null.");
+                }
+                if (sample.getInternalId() == null) {
+                    throw new IllegalArgumentException("InternalId for Sample " + sample.getStableId() + " is null.");
```
Comment (dippindots) [inline src/main/java/org/cbioportal/legacy/service/impl/GenericAssayServiceImpl.java:179]: Is this should be `sample. getInternalId()`? Other than that it looks good to me
```suggestion
                    throw new IllegalArgumentException("InternalId for Sample " + sample.getInternalId() + " is null.");
```

**Comment by KingAlex1985** [comment]
Hi @dippindots.
You are right. Thanks for the review. I have commited your suggestion.

**Comment by KingAlex1985** [comment]
@dippindots 
Can you approve it as reviewer? Or are you missing something else?

**Review by dippindots — APPROVED** [review]
LGTM

**Comment by KingAlex1985** [comment]
Hi guys. Thx for approval.

This PR was now approved by two members.
What is the next stept to get this PR into the master branch?

**Comment by dippindots** [comment]
@KingAlex1985 Thanks for fixing this issue! I merged it into master

**Comment by KingAlex1985** [comment]
Thank you also. :-)
