### PR TITLE
Fixing resource definition importer and updating file format

### LINKED ISSUE #9781: Resource Definition data importer should allow some optional fields
Current Resource Definition data importer doesn't allow optional fields (e.g. `DESCRIPTION`, `OPEN_BY_DEFAULT`, `PRIORITY`), this [pull request](https://github.com/cBioPortal/cbioportal/pull/9776) updated the documentation to indicate the current supported data format, but we should investigate and make it as expected.

### PR DESCRIPTION
**Pull request by dippindots**
Fix #9781
Describe changes proposed in this pull request:
- Updating importer to allow missing these three optional columns from resource definition data file (`DESCRIPTION, OPEN_BY_DEFAULT, PRIORITY`)
- Verified validator works well

### CODE REVIEW

File: core/src/main/java/org/mskcc/cbio/portal/scripts/ImportResourceDefinition.java [hunk 1]
```diff
@@ -228,6 +231,14 @@ private int findAndValidateColumnIndexInHeaders(String columnHeader, Map<String,
         " in file. Please check your file format and try again.");
     }
 
+    private int findAndValidateOptionalColumnIndexInHeaders(String columnHeader, Map<String, Integer> headerIndexMap) {
+        if (headerIndexMap.containsKey(columnHeader)) {
+            return headerIndexMap.get(columnHeader);
+        } else {
+            return MISSING_COLUMN_INDEX;
+        }
```
Comment (Luke-Sikina) [inline core/src/main/java/org/mskcc/cbio/portal/scripts/ImportResourceDefinition.java:239]:
```suggestion
        return headerIndexMap.getOrDefault(columnHeader, MISSING_COLUMN_INDEX);
```

**Review by Luke-Sikina — APPROVED** [review]

**Comment by dippindots** [comment]
@Luke-Sikina Thanks for the review, I just adopted this suggestion as a new commit.
