### PR TITLE
HRRS Properties Fix 

### LINKED ISSUE #6368: hrrs configuration crashes with properties.EXAMPLE
- [ ] Would be good to have the default for hrrs be:

    `hrrs.enable.logging=false`

    it should work when all these properties are missing from the properties file:

    ```
    hrrs.logging.filepath=
    hrrs.enable.logging=
    ```
    
    This is useful for people deploying a new version of the portal. They won't have to update their properties file

- [ ] In the EXAMPLE properties file good to mention what hrrs is. Mention that it is for debugging and probably good to comment out by default? The EXAMPLE file is included automatically as the default properties file when no properties file is given so better to not assign any values there

### PR DESCRIPTION
**Pull request by averyniceday**
# What? Why?
Fixes #6368 and #6377 - deployment was failing when hrrs properties were left blank.

Changes proposed in this pull request:
- `hrrs.enable.logging` defaults to `false`
- `hrrs.logging.filepath` defaults to `java.io.tmpdir/hrrs-logging.csv`

# Checks
- [ ] Runs on Heroku.
- [ ] Follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Follows the [Google Style Guide](https://github.com/google/styleguide).
- [ ] If this is a feature, the PR is to rc. If this is a bug fix, the PR is to master.

# Any screenshots or GIFs?
If this is a new visual feature please add a before/after screenshot or gif
here with e.g. [GifGrabber](http://www.gifgrabber.com/).

### CODE REVIEW

File: core/src/main/java/org/mskcc/cbio/portal/util/DebugHrrsFilter.java [hunk 1]
```diff
@@ -50,8 +51,10 @@
 
 public class DebugHrrsFilter extends Base64HrrsFilter {
 
+    private static final String DEFAULT_HRRS_LOGGING_NAME = "/hrrs-logging.csv";
+
     private static RotationConfig createRotationConfig() {
```
Comment (inodb) [inline core/src/main/java/org/mskcc/cbio/portal/util/DebugHrrsFilter.java]: @averyniceday 	is it possible to not run `super(createRotationConfig())` if `hrrs.enable.logging` is false? I assume `java.io.tmpdir` is always set but seems redundant to set up a logging file path if the whole feature is disabled?

Comment (averyniceday) [reply core/src/main/java/org/mskcc/cbio/portal/util/DebugHrrsFilter.java]: @inodb I'll look into it some more. But the superclass Base64HrrsFilter requires a RotationConfig argument passed in.

Comment (inodb) [reply core/src/main/java/org/mskcc/cbio/portal/util/DebugHrrsFilter.java]: @averyniceday 	I see - not worth spending too much time on it, but if it's an easy fix that would be great 👍 - gonna approve for now

Comment (averyniceday) [reply core/src/main/java/org/mskcc/cbio/portal/util/DebugHrrsFilter.java]: @inodb I changed it so this class will extend the HrrsFilter which doesn't require a RotationConfig passed in to the constructor. Then the writer/writerTarget is only set if the logging is enabled. I left the code for defaulting to the tempdir just in case someone enables logging with no path.

Comment (inodb) [reply core/src/main/java/org/mskcc/cbio/portal/util/DebugHrrsFilter.java]: @averyniceday perfect!

File: src/main/resources/portal.properties.EXAMPLE [hunk 2]
```diff
@@ -256,7 +256,9 @@ matchminer.url=
 matchminer.token=
 
 # enable/disable hrrs logging
-# filter which logs incoming web requests to specified logging directory
+# hrrs can be used for debugging - when enabled incoming web requests
+# will be logged into the specified directory
 # logs must be decrypted for more in-depth information
-hrrs.logging.filepath=
-hrrs.enable.logging=
+# see: https://github.com/vy/hrrs/blob/master/README.md
```
Comment (inodb) [inline src/main/resources/portal.properties.EXAMPLE]: nice
