### PR TITLE
Fixes Structural Variant Genes Table disappearing issue

### LINKED ISSUE #9011: Structural Variant Genes Table does not show up for archer
https://cbioportal.mskcc.org/study/summary?id=mskarcher
Screen Shot 2021-10-28 at 11 48 20 AM

There is a SQL error:

```
### The error may exist in URL [jar:file:/target/tomcat.8888/webapps/expanded/WEB-INF/lib/persistence-mybatis-0-unknown-version-SNAPSHOT.jar!/org/cbioportal/persistence/mybatis/AlterationCountsMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT              ENTREZ_GENE_ID AS entrezGeneId,             HUGO_GENE_SYMBOL AS hugoGeneSymbol,             COUNT(*) AS totalCount,             COUNT(DISTINCT(CASE_ID)) AS numberOfAlteredCases         FROM         (                        ) as JoinedTable                    GROUP BY ENTREZ_GENE_ID, HUGO_GENE_SYMBOL;
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') as JoinedTable

        GROUP BY ENTREZ_GENE_ID, HUGO_GENE_SYMBOL' at line 9
; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') as JoinedTable

        GROUP BY ENTREZ_GENE_ID, HUGO_GENE_SYMBOL' at line 9
```

### PR DESCRIPTION
**Pull request by ao508**
Fix #9011 

Addresses issue where structural variant genes table was not rendering for MSKARCHER.

For similar reasons the Oncoprint, Mutation Tab, and the Patient/Sample-view mutation tables were also not displaying fusion events for ARCHER.

## Before fix:
image
image

----
## After fix:

image
image

# Checks
- [ ] Runs on heroku
- [ ] Has tests or has a separate issue that describes the types of test that should be created. If no test is included it should explicitly be mentioned in the PR why there is no test.

# Notify reviewers
@kalletlak  @n1zea144 @inodb 

Signed-off-by: Angelica Ochoa <15623749+ao508@users.noreply.github.com>

### CODE REVIEW

**Comment by ao508** [comment]
@dippindots @alisman Where can I find the logic encoded in the Query button the study view page?

I'm still running into trouble with the Oncoprint rendering the fusion events for archer samples, although I've worked out the issues for rendering the structural variant genes table on the study view page and the mutation tables on the patient/sample view pages. 

Understanding what the frontend is expecting or executing when clicking that Query button will probably help shed more light on what exactly the backend is failing to do specifically for the Oncoprint.

File: service/src/main/java/org/cbioportal/service/impl/SampleServiceImpl.java [hunk 1]
```diff
@@ -174,31 +174,52 @@ public BaseMeta fetchMetaSamples(List<String> sampleListIds) {
...
+    }
 
+    private Boolean hasFusionsAsMutations(MolecularProfile p) {
+        return (p.getMolecularAlterationType().equals(MolecularProfile.MolecularAlterationType.MUTATION_EXTENDED) &&
+                p.getDatatype().equals("FUSION"));
+    }
+
+    private void processSamples(List<Sample> samples, String projection) {
         if (projection.equals("DETAILED")) {
+            // working in patient/sample view but not oncoprint
```
Comment (inodb) [inline service/src/main/java/org/cbioportal/service/impl/SampleServiceImpl.java:189]: @ao508 is this still true?

Comment (ao508) [reply service/src/main/java/org/cbioportal/service/impl/SampleServiceImpl.java:189]: nope, removing

File: model/src/main/java/org/cbioportal/model/MolecularProfile.java [hunk 2]
```diff
@@ -84,7 +84,9 @@ public MolecularAlterationType getMolecularAlterationType() {
         // https://github.com/cBioPortal/cbioportal/blob/8704058562c386afeac3082e50f39c1097d47983/core/src/main/java/org/mskcc/cbio/portal/util/GeneticProfileReader.java#L93
         // But somehow there was no migration for existing data. To resolve it replace FUSION alteration type by STRUCTURAL_VARIANT.
```
Comment (dippindots) [inline model/src/main/java/org/cbioportal/model/MolecularProfile.java:85]: Maybe we can also add some comment at here to mention that "fusion data could also come from a mutation profile"

File: model/src/main/java/org/cbioportal/model/MolecularProfile.java [hunk 3]
```diff
@@ -84,7 +84,9 @@ public MolecularAlterationType getMolecularAlterationType() {
...
         // TODO: remove this logic once all the fusions are migrated to structural variants
-        return molecularAlterationType.equals(MolecularAlterationType.FUSION)
+        return (molecularAlterationType.equals(MolecularAlterationType.FUSION) ||
+                (molecularAlterationType.equals(MolecularAlterationType.MUTATION_EXTENDED)
```
Comment (n1zea144) [inline model/src/main/java/org/cbioportal/model/MolecularProfile.java:89]: Since MSK piggy-backs fusions in mutation profile using FUSION as datatype.

File: model/src/main/java/org/cbioportal/model/MolecularProfile.java [hunk 4]
```diff
@@ -120,7 +122,8 @@ public void setDescription(String description) {
     public Boolean getShowProfileInAnalysisTab() {
         // TODO: remove this logic once the data is fixed (when all the fusions are migrated to structural variants)
         return showProfileInAnalysisTab
-                || (getMolecularAlterationType().equals(MolecularAlterationType.STRUCTURAL_VARIANT)
+                || ((molecularAlterationType.equals(MolecularAlterationType.STRUCTURAL_VARIANT)
+                        || molecularAlterationType.equals(MolecularAlterationType.MUTATION_EXTENDED))
```
Comment (n1zea144) [inline model/src/main/java/org/cbioportal/model/MolecularProfile.java:127]: Are the parenthesis correct here?  Should && only apply to datatype FUSION and MUTATION_EXTENDED?

File: service/src/main/java/org/cbioportal/service/impl/SampleServiceImpl.java [hunk 5]
```diff
@@ -174,31 +174,51 @@ public BaseMeta fetchMetaSamples(List<String> sampleListIds) {
...
                                           new HashSet<String>(sampleListRepository.getAllSampleIdsInSampleList(studyId + SEQUENCED)));
-                structuralVariantSampleIdsMap.put(studyId,
-                                       new HashSet<String>(sampleListRepository.getAllSampleIdsInSampleList(studyId + STRUCTURAL_VARIANT)));
+                // get sv samples from sequenced case list if fusions imported as mutations
+                Set<String> svSamples = new HashSet<>();
+                if (studiesProfiledWithFusionsAsMutations.contains(studyId)) {
+                    // use sample list that has already been fetched
+                    svSamples = new HashSet<>(sequencedSampleIdsMap.get(studyId));
+                } else {
+                    svSamples = new HashSet<String>(sampleListRepository.getAllSampleIdsInSampleList(studyId + STRUCTURAL_VARIANT));
```
Comment (dippindots) [inline service/src/main/java/org/cbioportal/service/impl/SampleServiceImpl.java:211]: I guess we can also use `new HashSet<>` to replace `new HashSet<String>`

File: persistence/persistence-mybatis/src/main/java/org/cbioportal/persistence/mybatis/AlterationMyBatisRepository.java [hunk 6]
```diff
@@ -62,7 +62,8 @@
         // if fusions were imported as a "mutations" profile then replace STRUCTURAL_VARIANT in
         // groupedIdentifiersByProfileType map with MUTATION_EXTENDED
         for (MolecularProfile profile : molecularProfileRepository.getMolecularProfiles(molecularProfileIds, "SUMMARY")) {
-            if (profile.getStableId().endsWith("mutations") && profile.getDatatype().equals("FUSION")) {
+            if (profile.getStableId().endsWith("mutations") && profile.getDatatype().equals("FUSION") &&
+                    groupedIdentifiersByProfileType.get(MolecularAlterationType.STRUCTURAL_VARIANT) != null) {
```
Comment (n1zea144) [inline persistence/persistence-mybatis/src/main/java/org/cbioportal/persistence/mybatis/AlterationMyBatisRepository.java:66]: Keeps from clobbering value keyed by MUTATION_EXTENDED.

File: service/src/main/java/org/cbioportal/service/impl/SampleServiceImpl.java [hunk 7]
```diff
@@ -174,31 +174,51 @@ public BaseMeta fetchMetaSamples(List<String> sampleListIds) {
         return sampleRepository.getSamplesByInternalIds(internalIds);
     }
 
-    private void processSamples(List<Sample> samples, String projection) {
+    private Boolean isProfiledWithSV(MolecularProfile p) {
+        return (p.getMolecularAlterationType().equals(MolecularProfile.MolecularAlterationType.STRUCTURAL_VARIANT) ||
+                hasFusionsAsMutations(p));
```
Comment (n1zea144) [inline service/src/main/java/org/cbioportal/service/impl/SampleServiceImpl.java:179]: Curious why you added hasFusionsAsMutations in this clause.

File: service/src/main/java/org/cbioportal/service/impl/SampleServiceImpl.java [hunk 8]
```diff
@@ -174,31 +174,51 @@ public BaseMeta fetchMetaSamples(List<String> sampleListIds) {
...
+    }
 
+    private Boolean hasFusionsAsMutations(MolecularProfile p) {
```
Comment (n1zea144) [inline service/src/main/java/org/cbioportal/service/impl/SampleServiceImpl.java:182]: We should add the usual:
TODO: remove this logic once all the fusions are migrated to structural variants

**Review by dippindots — COMMENTED** [review]
@ao508 Thanks for fixing this! Looks good to me! Just two minor comments.

I also would like to confirm that the issue was caused by this reason:
We were not able to find related samples because those samples are come from `mutation` profile, but we cannot fetch those data by using this method
```
sampleListRepository.getAllSampleIdsInSampleList(studyId + STRUCTURAL_VARIANT)
```
we need to fetch samples from sequenced samples like this:
```
sequencedSampleIdsMap.get(studyId)
```

Is that correct?

File: service/src/main/java/org/cbioportal/service/impl/SampleServiceImpl.java (hunk 5 above)
Comment (n1zea144) [inline service/src/main/java/org/cbioportal/service/impl/SampleServiceImpl.java:211]: Is this hit when the profile alteration type is STRUCTURAL_VARIANT?

File: service/src/main/java/org/cbioportal/service/impl/StructuralVariantServiceImpl.java [hunk 9]
```diff
@@ -141,23 +141,29 @@
             String molecularProfileId = molecularProfileIds.get(i);
             if (molecularProfileId.endsWith(molecularProfileUtil.STRUCTURAL_VARIANT_PROFILE_SUFFIX)) {
                 structuralVariantMolecularProfileIds.add(molecularProfileId);
-                structuralVariantSampleIds.add(sampleIds.get(i));
+                if (CollectionUtils.isNotEmpty(sampleIds))  {
```
Comment (n1zea144) [inline service/src/main/java/org/cbioportal/service/impl/StructuralVariantServiceImpl.java:144]: Nice.

**Review by n1zea144 — CHANGES_REQUESTED** [review]

File: model/src/main/java/org/cbioportal/model/MolecularProfile.java (hunk 4 above)
Comment (ao508) [reply model/src/main/java/org/cbioportal/model/MolecularProfile.java:127]: the logic before was SV && FUSION and since our case is mutations && FUSION I decided to consolidate the logic a little

File: service/src/main/java/org/cbioportal/service/impl/SampleServiceImpl.java (hunk 7 above)
Comment (ao508) [reply service/src/main/java/org/cbioportal/service/impl/SampleServiceImpl.java:179]: so that the sample status `isProfiledWithSV` can be set to true in the mskarcher cases

the lambda function was a little.. ugly with everything included right there so I moved it to a function but I can move it back here instead if that's preferred

File: service/src/main/java/org/cbioportal/service/impl/SampleServiceImpl.java (hunk 5 above)
Comment (ao508) [reply service/src/main/java/org/cbioportal/service/impl/SampleServiceImpl.java:211]: yes

**Comment by ao508** [comment]
> @ao508 Thanks for fixing this! Looks good to me! Just two minor comments.
> 
> I also would like to confirm that the issue was caused by this reason: We were not able to find related samples because those samples are come from `mutation` profile, but we cannot fetch those data by using this method
> 
> ```
> sampleListRepository.getAllSampleIdsInSampleList(studyId + STRUCTURAL_VARIANT)
> ```
> 
> we need to fetch samples from sequenced samples like this:
> 
> ```
> sequencedSampleIdsMap.get(studyId)
> ```
> 
> Is that correct?

Yep, that helped resolve the study view SV genes table rendering issue as well as the patient/sample page displaying those fusion events.

File: model/src/main/java/org/cbioportal/model/MolecularProfile.java (hunk 4 above)
Comment (n1zea144) [reply model/src/main/java/org/cbioportal/model/MolecularProfile.java:127]: Oh, the datatype is FUSION for SV alteration type?  Is that always true?

File: service/src/main/java/org/cbioportal/service/impl/SampleServiceImpl.java (hunk 7 above)
Comment (n1zea144) [reply service/src/main/java/org/cbioportal/service/impl/SampleServiceImpl.java:179]: I just noticed you are calling both below, so didn't think it was necessary.

**Review by n1zea144 — APPROVED** [review]

**Review by inodb — COMMENTED** [review]
Thanks for fixing this!

We are currently not running the full suite of tests for the localdb nor are we running the tests for the backend. It would be good to run these thru at least the full set of localdb tests before merging. This is the PR that re-introduces many of the localdb tests: https://github.com/cBioPortal/cbioportal/pull/9015. Let's wait until that is merged

**Comment by dippindots** [comment]
Tests looks good, I am going to merge this into master.
