### PR TITLE
Latest fixes in network view,SBGN view

### LINKED ISSUE #1181: JS error in Network
http://bit.ly/21xFzJa

image

### PR DESCRIPTION
**Pull request by istemi-bahceci**
Fixed #1181, #1096, #1099, #1100, #1186, #1052

### CODE REVIEW

File: portal/src/main/webapp/js/lib/SBGNViz.js/sample-app/index.html [hunk 1]
```diff
@@ -75,11 +74,10 @@
                                 <b class="caret"></b>
                             </a>
                             <ul class="dropdown-menu">
-                                <li><a href="#" id="select-edit">Select/Edit</a></li>
+                                <!-- <li><a href="#" id="select-edit">Select/Edit</a></li>
```
Comment (jjgao) [inline portal/src/main/webapp/js/lib/SBGNViz.js/sample-app/index.html]: Is there any reason to keep the code? If not, could you just remove them instead of commenting?
