### PR TITLE
Fix for frequency in multi-study view 

### LINKED ISSUE #10967: Mutation count in combined studies with genepanels seems to be incorrect
The combined studyview shows that the IPO13 gene has a 100% mutation frequency (in the mutations table). However, upon closer inspection, the mutations table does not take along profiled genes without mutations in it's calculation. According to the results view the actual mutation rate is 24% as there are multiple samples in the second study that are profiled but do not have mutations.

[Study view of combined study with 100% mutation counts](https://www.cbioportal.org/study/summary?id=brca_hta9_htan_2022%2Cnsclc_mskcc_2015). See bottom of image.

image

[Results view of IPO13 gene with 24% mutation rate](https://www.cbioportal.org/results?cancer_study_list=brca_hta9_htan_2022%2Cnsclc_mskcc_2015&tab_index=tab_visualize&profileFilter=mutations%2Ccna&case_set_id=all&Action=Submit&gene_list=IPO13&show_samples=true)

image

### PR DESCRIPTION
**Pull request by eugeniomazzone**
Fix #10967

Describe changes proposed in this pull request:
- Function _AlterationCountServiceUtil.setupAlterationGeneCountsMap_ now initialize the profiledCases to 0.
- Added an additional piece of code (after above function is called) in _AlterationCountServiceImpl_ to update the number of profiled samples with the correct one, for each study and each gene.

After the fix, the frequency displayed on the multi-study view appear to be correct as it's 23.8% as expected instead of 100%.

Before fix: 
Before1
Before2

After fix:
After1
After2

### CODE REVIEW

**Comment by zeynepkaragoz** [comment]
@inodb Eugenio worked on fixing one of the open issues, could you point us to some potential reviewers please?

**Comment by inodb** [comment]
@haynescd @alisman this is a fix in legacy code for determining alteration frequency in multi-study query. Thoughts?

File: src/main/java/org/cbioportal/service/impl/AlterationCountServiceImpl.java [hunk 1]
```diff
@@ -280,6 +281,39 @@ private <S extends AlterationCountBase> Pair<List<S>, Long> getAlterationGeneCou
...
+                        if (!alterationCountByGene.getMatchingGenePanelIds().isEmpty()) {
+                            matchingGenePanelIds.addAll(alterationCountByGene.getMatchingGenePanelIds());
+                        }
+                        if (!datum.getMatchingGenePanelIds().isEmpty()) {
+                            matchingGenePanelIds.addAll(datum.getMatchingGenePanelIds());
+                        }
+                        alterationCountByGene.setMatchingGenePanelIds(matchingGenePanelIds);
+                        totalResult.put(key, alterationCountByGene);
+                    });
+                });
```
Comment (haynescd) [inline src/main/java/org/cbioportal/service/impl/AlterationCountServiceImpl.java:316]: Lets break this out into functions instead of one big anonymous function. Also, can we add some comments

File: src/main/java/org/cbioportal/service/util/AlterationCountServiceUtil.java [hunk 2]
```diff
@@ -148,7 +148,8 @@ public static <S extends AlterationCountBase> void setupAlterationGeneCountsMap(
                 S alterationCountByGene = totalResult.get(key);
                 alterationCountByGene.setTotalCount(alterationCountByGene.getTotalCount() + datum.getTotalCount());
                 alterationCountByGene.setNumberOfAlteredCases(alterationCountByGene.getNumberOfAlteredCases() + datum.getNumberOfAlteredCases());
-                alterationCountByGene.setNumberOfProfiledCases(alterationCountByGene.getNumberOfProfiledCases() + datum.getNumberOfProfiledCases());
+                alterationCountByGene.setNumberOfProfiledCases(0);
+                //alterationCountByGene.setNumberOfProfiledCases(alterationCountByGene.getNumberOfProfiledCases() + datum.getNumberOfProfiledCases());
```
Comment (haynescd) [inline src/main/java/org/cbioportal/service/util/AlterationCountServiceUtil.java:152]: Why is it just commented out?

File: src/main/java/org/cbioportal/service/impl/AlterationCountServiceImpl.java (hunk 1 above)
Comment (eugeniomazzone) [reply src/main/java/org/cbioportal/service/impl/AlterationCountServiceImpl.java]: Moved the code to a separate function _updateAlterationGeneCountsMap_ mimicking  _setupAlterationGeneCountsMap_

**Comment by fuzhaoyuan** [comment]
Tests are not passing. Could you run `mvn clean package` in your local environment?

**Comment by alisman** [comment]
It looks like legacy is not reporting "not_profiled" status correctly. Compare 

```
curl 'http://localhost:8082/api/column-store/mutation-data-counts/fetch?projection=SUMMARY' \
  -H 'Accept: application/json' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: JSESSIONID=0B4EB4ED93E52DB8CA6991CBFAAA88CB' \
  -H 'Origin: http://localhost:8082' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://localhost:8082/study/summary?id=brca_tcga_pan_can_atlas_2018' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw '{"genomicDataFilters":[{"hugoGeneSymbol":"EGFR","profileType":"mutations"}],"studyViewFilter":{"mutationDataFilters":[{"hugoGeneSymbol":"EGFR","profileType":"mutations","values":[[{"value":"NOT_MUTATED"}]],"categorization":"MUTATED"}],"studyIds":["brca_tcga_pan_can_atlas_2018"],"alterationFilter":{"copyNumberAlterationEventTypes":{"AMP":true,"HOMDEL":true},"mutationEventTypes":{"any":true},"structuralVariants":null,"includeDriver":true,"includeVUS":true,"includeUnknownOncogenicity":true,"includeUnknownTier":true,"includeGermline":true,"includeSomatic":true,"includeUnknownStatus":true,"tiersBooleanMap":{}}}}'

```

**Comment by eugeniomazzone** [comment]
Today, I've looked at the tests (haven't done that before). I've added the new function to the tests and I've initialized a _MolecularProfileCaseIdentifier_  with generic names for each sample to make it work. Finally, it's now specified that now some function are called twice.

File: src/main/java/org/cbioportal/service/util/AlterationCountServiceUtil.java [hunk 3]
```diff
@@ -1,20 +1,10 @@
...
 
 import org.apache.commons.math3.util.Pair;
-import org.cbioportal.model.AlterationCountBase;
-import org.cbioportal.model.AlterationCountByGene;
-import org.cbioportal.model.CopyNumberCountByGene;
-import org.cbioportal.model.Gistic;
-import org.cbioportal.model.GisticToGene;
-import org.cbioportal.model.MolecularProfile;
-import org.cbioportal.model.MutSig;
+import org.cbioportal.model.*;
```
Comment (fuzhaoyuan) [inline src/main/java/org/cbioportal/service/util/AlterationCountServiceUtil.java:4]: Could you release the imports so they're not abbreviated? In this case we would know which classes are being used. If it's a auto feature in the IDE it can be turned off.

File: src/main/java/org/cbioportal/service/impl/AlterationCountServiceImpl.java [hunk 4]
```diff
@@ -280,6 +281,21 @@ private <S extends AlterationCountBase> Pair<List<S>, Long> getAlterationGeneCou
                     }
                     AlterationCountServiceUtil.setupAlterationGeneCountsMap(studyAlterationCountByGenes, totalResult);
                 });
+
+            // Update number of profiled case considering the whole selected sample cohort
```
Comment (fuzhaoyuan) [inline src/main/java/org/cbioportal/service/impl/AlterationCountServiceImpl.java:285]: For this second part it looks mostly duplicated from above old code. Is this intended? Could you elaborate?

File: src/main/java/org/cbioportal/service/util/AlterationCountServiceUtil.java [hunk 5]
```diff
@@ -159,10 +149,34 @@ public static <S extends AlterationCountBase> void setupAlterationGeneCountsMap(
                 alterationCountByGene.setMatchingGenePanelIds(matchingGenePanelIds);
                 totalResult.put(key, alterationCountByGene);
             } else {
+                datum.setNumberOfProfiledCases(0); //Ensure number of cases is initialized to zero
                 totalResult.put(key, datum);
             }
         });
     }
+    
+    public static <S extends AlterationCountBase> void updateAlterationGeneCountsMap(
```
Comment (fuzhaoyuan) [inline src/main/java/org/cbioportal/service/util/AlterationCountServiceUtil.java:158]: Also some comments explaining this function would be great. We're implementing new coding guidelines so it'll help us to add JavaDocs in the future. Thanks

**Comment by fuzhaoyuan** [comment]
Hi @eugeniomazzone I left some more comments. Also I'm seeing there're 5 new issues from SonarQube results. Could you see to address that? Thank you!

File: src/main/java/org/cbioportal/service/util/AlterationCountServiceUtil.java (hunk 5 above)
Comment (eugeniomazzone) [reply src/main/java/org/cbioportal/service/util/AlterationCountServiceUtil.java:170]: I've added some comments int he code for clarity.

File: src/main/java/org/cbioportal/service/util/AlterationCountServiceUtil.java (hunk 3 above)
Comment (eugeniomazzone) [reply src/main/java/org/cbioportal/service/util/AlterationCountServiceUtil.java]: Imports were released and are now fully visible without abbreviations

File: src/main/java/org/cbioportal/service/impl/AlterationCountServiceImpl.java (hunk 4 above)
Comment (eugeniomazzone) [reply src/main/java/org/cbioportal/service/impl/AlterationCountServiceImpl.java:283]: The function's structure is mostly inspired from _**setup**AlterationGeneCountsMap_, although _**update**AlterationGeneCountsMap_  use similar arguments in a different way. In the update function, TotalResults is now used in the place of _studyAlterationCountByGenes_ and updated with identifiers information (_studyMolecularProfileCaseIdentifiers_).
Additionally, I've deleted a part of the function that was duplicated and was re-updating the gene panel information.

**Comment by eugeniomazzone** [comment]
I've updated the PR with the required changes. Now there are more detailed comments for code changes, the imports were released and the issues from SonarQube should have been adressed.

**Comment by eugeniomazzone** [comment]
I've updated the PR with the required changes. Now there are more detailed comments for code changes, the imports were released and the issues from SonarQube should have been adressed.

**Comment by fuzhaoyuan** [comment]
Hi @eugeniomazzone thank you for the update. I see there's still one import that is abbreviated in tests (usually it's a IDE auto feature that can be turned off). And could you rebase your PR onto the latest `master` branch? Other than these I think it's good to go. Thanks!

**Comment by eugeniomazzone** [comment]
Hi @alisman! I've release the import and rebase the fork to master.

**Review by fuzhaoyuan — APPROVED** [review]

**Comment by eugeniomazzone** [comment]
I've seen there was some tests failing due to a missing import. 
I've now included it and locally it pass all the tests :)
