### PR TITLE
Fix Generic Assay entities deletion error and profile property error

### LINKED ISSUE #9358: (Importer) Generic Assay entities don't get deleted correctly
Generic Assay entities don't get deleted correctly when the profile that gets deleted is the only one profile related.

When deleting a study, we should do as follows:

- Find all Generic Assay profiles in this study
- Go through each profile one by one, try to determine if we need to delete entities per profile instead of per study

We should also add some test cases for deleting Generic Assay entities.

- [x] Change deletion logic to determine if we need to delete entities per profile

### LINKED ISSUE #9415: (Importer) Generic Assay profile property error
When importing a Generic Assay profile, the property `pivot_threshold_value` and `value_sort_order` should be imported separately.

### PR DESCRIPTION
**Pull request by dippindots**
Fix #9358
Fix #9415

This pr address two things:

- Generic Assay entities don't get deleted correctly when the profile that gets deleted is the only one profile related. When deleting a study, we should do as follows: 
    - Find all Generic Assay profiles in this study. 
    - Go through each profile one by one, try to determine if we need to delete entities per profile instead of per study

- When importing a Generic Assay profile, the property pivot_threshold_value and value_sort_order should be imported separately.

### CODE REVIEW

File: core/src/main/java/org/mskcc/cbio/portal/dao/DaoGenericAssay.java [hunk 1]
```diff
@@ -143,4 +147,42 @@ public static boolean geneticEntitiesOnlyExistInSingleStudy(int cancerStudyId) t
...
+     * check and delete generic assay meta records profile by profile
+     * @throws DaoException
+     */
+    public static void checkAndDeleteGenericAssayMetaInStudy(int internalCancerStudyId) throws DaoException {
+        List<GeneticProfile> geneticProfiles = DaoGeneticProfile.getAllGeneticProfiles(internalCancerStudyId);
+        List<GeneticProfile> genericAssayProfiles = geneticProfiles.stream().filter(profile -> profile.getGeneticAlterationType() == GeneticAlterationType.GENERIC_ASSAY).collect(Collectors.toList());
+        List<Pair<Integer, String>> deleteGenericAssayStatements = new ArrayList<>();
+
+        for (GeneticProfile profile : genericAssayProfiles) {
+            if (DaoGenericAssay.geneticEntitiesOnlyExistInSingleStudy(profile.getGeneticProfileId())) {
```
Comment (n1zea144) [inline core/src/main/java/org/mskcc/cbio/portal/dao/DaoGenericAssay.java:162]: Profiles can have different generic entities so this has to be checked each iteration through the loop.

**Review by n1zea144 — APPROVED** [review]
