### PR TITLE
fixing null point exception when queried MT genes not found in the re…

### LINKED ISSUE #6504: Null point exception from Expression Web Service when queried mitochondrial genes not found from Reference Genome Genes DB table
Currently Enrichment Expression Web Service throws a null point exception when queried genes such as mitochondrial genes are not found in the reference genome gene table. 
Screen Shot 2019-08-08 at 4 29 33 PM

### PR DESCRIPTION
**Pull request by khzhu**
…ference genome gene DB table

# What? Why?
Fix #6504 

Changes proposed in this pull request:
- a
- b

# Checks
- [ ] Runs on Heroku.
- [ ] Follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Follows the [Google Style Guide](https://github.com/google/styleguide).
- [ ] If this is a feature, the PR is to rc. If this is a bug fix, the PR is to master.
- [ ] If this is a bug fix, create a unit and/or e2e test, or explain why that cannnot be done.

# Any screenshots or GIFs?
If this is a new visual feature please add a before/after screenshot or gif
here with e.g. [GifGrabber](http://www.gifgrabber.com/).

### CODE REVIEW

**Comment by khzhu** [comment]
@kalletlak , can I please have your review. Thanks!

File: service/src/main/java/org/cbioportal/service/impl/ExpressionEnrichmentServiceImpl.java [hunk 1]
```diff
@@ -137,9 +137,16 @@
                 .collect(Collectors.groupingBy(ReferenceGenomeGene::getEntrezGeneId));
 
         expressionEnrichments.forEach(expressionEnrichment -> {
-            ReferenceGenomeGene gene = geneMapByEntrezId.get(expressionEnrichment.getEntrezGeneId()).get(0);
-            expressionEnrichment.setHugoGeneSymbol(gene.getHugoGeneSymbol());
-            expressionEnrichment.setCytoband(gene.getCytoband());
+            try {
```
Comment (kalletlak) [inline service/src/main/java/org/cbioportal/service/impl/ExpressionEnrichmentServiceImpl.java]: Should we remove this(setting Hugo gene symbol and cytoband), since we are getting gene info for all genes in the front-end.

Comment (khzhu) [reply service/src/main/java/org/cbioportal/service/impl/ExpressionEnrichmentServiceImpl.java]: let me check if we back fill cytobands for expression in frontend.

Comment (khzhu) [reply service/src/main/java/org/cbioportal/service/impl/ExpressionEnrichmentServiceImpl.java]: you are right. We can remove set up for cytobands (it is done in, but we still need to set hugoSymbols.

Comment (kalletlak) [reply service/src/main/java/org/cbioportal/service/impl/ExpressionEnrichmentServiceImpl.java]: ok. I think there are couple of ways to do it
1. we could you `hugoSymbols` from the response of `reference-genome-genes` api
2. set `hugoSymbols` similar to what's done for mutation or copy number enrichments api

Comment (khzhu) [reply service/src/main/java/org/cbioportal/service/impl/ExpressionEnrichmentServiceImpl.java]: @kalletlak , we have to set hugoSymbols for all alterations in the backend, not in frontend. Please check the function makeEnrichmentDataPromise see if you agree. 
```
                // add cytoband from reference gene
                for (const d of data) {
                    const refGene = params.referenceGenesPromise.result![d.hugoGeneSymbol];

                    if (refGene)
                        d.cytoband = refGene.cytoband;
                }
```

Comment (khzhu) [reply service/src/main/java/org/cbioportal/service/impl/ExpressionEnrichmentServiceImpl.java]: @kalletlak , changes made. please have your final review. thanks!

File: service/src/main/java/org/cbioportal/service/impl/ExpressionEnrichmentServiceImpl.java [hunk 2]
```diff
@@ -131,15 +131,21 @@
...
                 .stream()
-                .collect(Collectors.groupingBy(ReferenceGenomeGene::getEntrezGeneId));
+                .collect(Collectors.groupingBy(Gene::getEntrezGeneId));
 
         expressionEnrichments.forEach(expressionEnrichment -> {
-            ReferenceGenomeGene gene = geneMapByEntrezId.get(expressionEnrichment.getEntrezGeneId()).get(0);
-            expressionEnrichment.setHugoGeneSymbol(gene.getHugoGeneSymbol());
-            expressionEnrichment.setCytoband(gene.getCytoband());
+            Gene gene = geneMapByEntrezId.get(expressionEnrichment.getEntrezGeneId()).get(0);
+            if (gene != null) {
```
Comment (kalletlak) [inline service/src/main/java/org/cbioportal/service/impl/ExpressionEnrichmentServiceImpl.java]: I think gene won't be null any time, because only validated data would be loaded in to database

**Comment by kalletlak** [comment]
@khzhu I think you need to update tests

File: service/src/main/java/org/cbioportal/service/impl/ExpressionEnrichmentServiceImpl.java (hunk 2 above)
Comment (kalletlak) [reply service/src/main/java/org/cbioportal/service/impl/ExpressionEnrichmentServiceImpl.java]: if its null then you should remove that particular `expressionEnrichment` object from response
