### PR TITLE
Fix #7372

### LINKED ISSUE #7372: Mouse seed database 2.12.3: cancer types and gene names not found
Hi, 
I recently switched to seed-cbioportal_mm10_v2.12.3 and now I have problems with the data validation. Previously I was working with 2.3.1, which was working fine.

First of all there is a problem with the cancer types:

```
ERROR: cancer_type_data.txt: line 1: column 5: Unknown parent for cancer type 'pdac'; value encountered: 'Pancreas'
INFO: cancer_type_data.txt: line 1: New disease type will be added to the portal; value encountered: 'pdac'
INFO: cancer_type_data.txt: Validation of file complete
INFO: cancer_type_data.txt: Read 1 lines. Lines with warning: 0. Lines with error: 1
ERROR: -: Cancer type of study is neither known to the portal nor defined in a cancer_type file; value encountered: 'pdac'

```

After I changed the value to "tissue" as a wildcard, this step continues without problems. 
Anyways I soon run into the next problem regarding gene names:

```
Reading data from:  /study/expression_data.txt
Recaching...
Finished recaching...
--> profile id:  1
--> profile name:  A name for the expression data
--> genetic alteration type:  MRNA_EXPRESSION
--> total number of samples: 2
--> total number of data lines:  35413
--> records inserted into `sample_profile` table: 2
--> total number of data entries skipped (see table below):  35413
org.mskcc.cbio.portal.dao.DaoException: Something has gone wrong!  I did not save any records to the database!
at org.mskcc.cbio.portal.scripts.ImportTabDelimData.importData(ImportTabDelimData.java:281)
at org.mskcc.cbio.portal.scripts.ImportProfileData.run(ImportProfileData.java:109)
at org.mskcc.cbio.portal.scripts.ConsoleRunnable.runInConsole(ConsoleRunnable.java:145)
at org.mskcc.cbio.portal.scripts.ImportProfileData.main(ImportProfileData.java:134)

Warnings / Errors:
-------------------
0.  CDC2        983 in config file [resources/gene_symbol_disambiguation.txt]is not valid. You should either update this file or update th   e `gene` and `gene_alias` tables to fix this.; 1x
1.  Entrez_Id null not found. Record will be skipped for this gene.; 35413x
2.  MLL2        8085 in config file [resources/gene_symbol_disambiguation.txt]is not valid. You should either update this file or update t   he `gene` and `gene_alias` tables to fix this.; 1x

ABORTED!
java.lang.RuntimeException: org.mskcc.cbio.portal.dao.DaoException: Something has gone wrong!  I did not save any records to the database!

```

If I rerun this with a debug set with Entrez IDs (mixed mouse and human just in case) the results is almost the same:
```
1.  Entrez_Id 67437 not found. Record will be skipped for this gene.; 1x
2.  Entrez_Id 6746 not found. Record will be skipped for this gene.; 1x
3.  Entrez_Id 6747 not found. Record will be skipped for this gene.; 1x
```

Can it be, that the value lookup tables in the seed databas are incomplete? Or am I doing something wrong with the commands? 

This is how I run the import:
```
docker run -it --rm --net cbio-net \
    -v /home/username/Documents/cbioportal_IMOdb/portal.properties:/cbioportal/portal.properties:ro \
    -v "/mnt/3TBVol/cbioportal_IMOdb_data/ExampleStudy1:/study:ro" \
    -v "/home/username/Documents/cbioportal_IMOdb/upload_reports:/report" \
    cbioportal/cbioportal:latest \
    metaImport.py -u http://cbioportal-container:8080 -s /study --html=/report/report.html \
	-species mouse -ucsc mm10 -ncbi 38 \
	--override_warning	
```

Thank you very much!

### PR DESCRIPTION
**Pull request by jjgao**
Fix #7372. 

`resources/gene_symbol_disambiguation.txt` is human specific. When running a mouse portal, there will be a run time exception. This PR is to fix the run time exception.

# Checks
- [ ] Runs on heroku
- [ ] Has tests or has a separate issue that describes the types of test that should be created. If no test is included it should explicitly be mentioned in the PR why there is no test.
- [ ] The commit log is comprehensible. It follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Is this PR adding logic based on one or more **clinical** attributes? If yes, please make sure validation for this attribute is also present in the data validation / data loading layers (in backend repo) and documented in [File-Formats Clinical data section](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#clinical-data)!

# Any screenshots or GIFs?
If this is a new visual feature please add a before/after screenshot or gif
here with e.g. [Giphy CAPTURE](https://giphy.com/apps/giphycapture) or [Peek](https://github.com/phw/peek)

# Notify reviewers
Read our [Pull request merging
policy](../CONTRIBUTING.md#pull-request-merging-policy). It can help to figure out who worked on the
file before you. Please use `git blame <filename>` to determine that
and notify them either through slack or by assigning them as a reviewer on the PR

### CODE REVIEW

File: core/src/main/java/org/mskcc/cbio/portal/dao/DaoGeneOptimized.java [hunk 1]
```diff
@@ -95,11 +95,12 @@ private synchronized void fillCache() {
...
                     ProgressMonitor.logWarning(line+" in config file [resources" + GENE_SYMBOL_DISAMBIGUATION_FILE +
                             "]is not valid. You should either update this file or update the `gene` and `gene_alias` tables to fix this.");
+                } else {
+                    disambiguousGenes.put(parts[0], gene);
                 }
-                disambiguousGenes.put(parts[0], gene);
             }
             in.close();
-        } catch(IOException e) {
+        } catch(Exception e) {
```
Comment (n1zea144) [inline core/src/main/java/org/mskcc/cbio/portal/dao/DaoGeneOptimized.java:103]: Just curious, are Exceptions besides IOException thrown here?

Comment (jjgao) [reply core/src/main/java/org/mskcc/cbio/portal/dao/DaoGeneOptimized.java:103]: There was a RuntimeException, but should be fixed with the fix above.

Just trying to cast a wider net since not being able to load the disambiguate file is not critical issue and shouldn't bring down the application.

Comment (jjgao) [reply core/src/main/java/org/mskcc/cbio/portal/dao/DaoGeneOptimized.java:103]: No it was b/c the entrez IDs in the file are human IDs and therefore do not exist in mouse genes, ie. gene==NULL. As a result, `disambiguousGenes.put(parts[0], gene);` throws runtime exception.

Comment (jjgao) [reply core/src/main/java/org/mskcc/cbio/portal/dao/DaoGeneOptimized.java:103]: I am ok to revert this one as long as we get the change to line 99 in :)

**Comment by jjgao** [comment]
@n1zea144 @sheridancbio I have reverted the change and only capture IOException. Adding `else` should be enough to fix the bug. Would you please review again?
