### PR TITLE
10584 fix tutorials

### LINKED ISSUE #10584: /tutorials broken in v6
https://www.cbioportal.org/tutorials

Should go to:

https://docs.cbioportal.org/user-guide/overview/#tutorial-slides

### PR DESCRIPTION
**Pull request by uklineale**
Fix #10584  (see https://help.github.com/en/articles/closing-issues-using-keywords)

Describe changes proposed in this pull request:
- Revert the routes but clean it up a bit
- Add tutorials redirect

# Checks
- [ ] The commit log is comprehensible. It follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). We can fix this during merge by using a squash+merge if necessary
- [ ] Has tests or has a separate issue that describes the types of test that should be created. If no test is included it should explicitly be mentioned in the PR why there is no test.
- [ ] Is this PR adding logic based on one or more **clinical** attributes? If yes, please make sure validation for this attribute is also present in the data validation / data loading layers (in backend repo) and documented in [File-Formats Clinical data section](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#clinical-data)!
- [ ] Make sure your PR has one of the labels defined in https://github.com/cBioPortal/cbioportal/blob/master/.github/release-drafter.yml

# Any screenshots or GIFs?
If this is a new visual feature please add a before/after screenshot or gif
here with e.g. [Giphy CAPTURE](https://giphy.com/apps/giphycapture) or [Peek](https://github.com/phw/peek)

# Notify reviewers
Read our [Pull request merging
policy](../CONTRIBUTING.md#pull-request-merging-policy). It can help to figure out who worked on the
file before you. Please use `git blame <filename>` to determine that
and notify them either through slack or by assigning them as a reviewer on the PR

### CODE REVIEW

File: src/main/java/org/cbioportal/WebAppConfig.java [hunk 1]
```diff
@@ -33,9 +35,31 @@ public void addResourceHandlers(ResourceHandlerRegistry registry) {
 	public void addViewControllers(ViewControllerRegistry registry) {
 		registry.addRedirectViewController("/api", swaggerRedirectUrl);
 		registry.addRedirectViewController("/installations", "https://installationmap.netlify.app/");
+		registry.addRedirectViewController("/tutorials", "https://docs.cbioportal.org/user-guide/overview/#tutorial-slides");
```
Comment (inodb) [inline src/main/java/org/cbioportal/WebAppConfig.java:38]:
```suggestion
		registry.addRedirectViewController("/tutorials", "https://docs.cbioportal.org/user-guide/overview/#tutorial-slides");
		registry.addRedirectViewController("/oql", "https://docs.cbioportal.org/user-guide/oql/");
```

**Review by JREastonMarks — APPROVED** [review]
lgtm
