### PR TITLE
Sample Quick Search 500s

### LINKED ISSUE #6813: 500 error on quick search mskcc portal when user does not have access to all studies
Can be reproduced by running an authenticated portal and logging in with a user that does not have access to all studies

```
 The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
        org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
        org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        javax.servlet.http.HttpServlet.service(HttpServlet.java:635)        org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)        javax.servlet.http.HttpServlet.service(HttpServlet.java:742)        org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)        org.mskcc.cbio.portal.util.XssFilter.doFilter(XssFilter.java:65)        org.cbioportal.web.util.ResettableHttpServletRequestFilter.doFilter(ResettableHttpServletRequestFilter.java:29)        org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:124)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
        org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
        org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
        org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
        org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
        org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
        org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
        com.vlkan.hrrs.servlet.HrrsFilter.doFilter(HrrsFilter.java:85)
        org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:441)
        org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:169)
</pre><p><b>Root Cause</b></p><pre>java.lang.NullPointerException
```

This prolly needs testing as well but we first need to set up a way to test authenticated portals. Created an issue to keep track of the testing part of this issue: https://github.com/cBioPortal/cbioportal/issues/6814

### PR DESCRIPTION
**Pull request by Luke-Sikina**
Fix #6813 (see https://help.github.com/en/articles/closing-issues-using-keywords)

Describe changes proposed in this pull request:
- Cause
    - The sample quick search endpoint was breaking when given a request
    in an environment that requires auth and with a projection of META
    - It was breaking because the study service method it calls has a
    post filter that calls `split` on the study groups. When the projection
    was META, the groups field was `null` and the filter NPEed
- Solution
    - Make the study service request with a projection of SUMMARY
    regardless of the main request's projection

### CODE REVIEW

File: web/src/main/java/org/cbioportal/web/SampleController.java [hunk 1]
```diff
@@ -100,7 +100,7 @@ private boolean usingAuth() {
             studyIds = studyService
                 .getAllStudies(
                     null,
-                    projection.name(),
+                    Projection.SUMMARY.name(), // force to summary so that post filter doesn't NPE
```
Comment (Luke-Sikina) [inline web/src/main/java/org/cbioportal/web/SampleController.java]: I'm having trouble testing this. I would like to write a test where I set the `authenticate` variable (line 60) to a value and then verify that the sampleService is called with the correct projection when I when I do a request with projection META.

I couldn't do this because I didn't see a way to expose the controller so that I could change that field via reflection.
