### PR TITLE
App should fallback gracefully when Redis cache is unavailable

### LINKED ISSUE #11646: [BUG] App crashes when Redis cache is unavailable – should fallback gracefully
**Describe the bug**
When Redis cache is unavailable (e.g. due to connection failure or downtime), the application fails to start or operate correctly. It does not fallback to a non-cached mode as expected.

**To Reproduce**
1. Stop or block access to the Redis instance used by the app
2. Start the application
3. Observe startup failure or runtime errors related to Redis connectivity

**Expected behavior**
Observe startup failure or runtime errors related to Redis connectivity

**Screenshots**

**Additional context**
This issue causes unnecessary downtime and affects reliability. A fallback mechanism would improve resilience in environments where Redis may be temporarily inaccessible.

### PR DESCRIPTION
**Pull request by dippindots**
Fix #11646 

## Key Changes Made

1. **Modified CustomRedisCachingProvider.java**:
- Added graceful error handling for Redis connection failures
- Wrapped cache clearing operations in try-catch to prevent startup failures
- Added proper logging when Redis is unavailable
2. **Created NoOpCacheManager.java**:
- Implements a no-op cache manager that does nothing when Redis is unavailable
- Provides detailed logging for cache operations
- Ensures the application can function without Redis by falling back to database queries
- Properly handles value loaders and exception propagation
3. **Enhanced CustomRedisCache.java**:
- Added null checks for redissonClient to handle Redis unavailability during runtime
- Wrapped all Redis operations in try-catch blocks
- Added graceful fallback behavior when Redis operations fail
4. **Redis Health Tracking**:
- Added Redis health tracking that prevents repeated connection attempts when Redis is down
- Added configurable health check interval: `redis.health_check_interval_ms` property (default: `30` seconds)
- When Redis is marked as unhealthy, operations skip Redis entirely and go straight to database queries
- After the configured interval, Redis health status resets to allow retrying
5. **Improved logging to indicate when Redis is unavailable**
- Improved LoggingCacheErrorHandler.java:
- Enhanced error handling to prevent exceptions from propagating
- Added informative logging messages
- Ensures Redis failures don't crash the application
6. **Updated Documentation**:
- Updated [application.properties-Reference.md](http://application.properties-reference.md/) to clarify that Redis is always optional
- Added clear documentation about the fallback behavior
7. **Created Tests**:
- **NoOpCacheManagerTest.java**: Tests the no-op cache behavior
- **CustomRedisCachingProviderTest.java**: Tests Redis connection failure scenarios
- **RedisConnectionFailureTest.java**: Tests complete fallback scenarios
- **RedisConfigTest.java**: Tests Redis configuration components
- **RedisRuntimeFailureTest**: Tests runtime Redis failures

## How It Works

1. **When Redis is available**: The application uses Redis for caching as normal
2. **When Redis is unavailable when app is being created**:
- The application starts successfully without Redis
- Application continues to function when Redis becomes unavailable during runtime
- All cache operations become no-op (do nothing)
- Database queries are executed directly when cache misses occur
- Proper logging indicates Redis unavailability
- No exceptions are thrown that would crash the application
3. **When Redis is unavailable when app is running**:
- When Redis fails, it's marked as "unhealthy" and a timestamp is recorded
- Subsequent Operations: For the next 30 seconds (configurable), all cache operations skip Redis entirely
- Fast Fallback: Operations go directly to database queries without any Redis connection attempts
- Automatic Recovery: After the interval, Redis is considered healthy again for retry

## Test Results

- Redis connection failure scenarios
- No-op cache behavior
- Health tracking behavior
- Error handling and logging
- Configuration component behavior
- Value loader functionality

### CODE REVIEW

File: src/main/java/org/cbioportal/legacy/persistence/util/NoOpCacheManager.java [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+  }
+
+  @Override
+  public Collection<String> getCacheNames() {
+    return Collections.emptyList();
+  }
+
+  /**
+   * No-op implementation of Cache that does nothing. When Redis is unavailable, this ensures the
+   * application can still function by falling back to database queries.
```
Comment (onursumer) [inline src/main/java/org/cbioportal/legacy/persistence/util/NoOpCacheManager.java]: This comment looks redundant to me. Maybe only keep the one at the top level class?

Comment (dippindots) [reply src/main/java/org/cbioportal/legacy/persistence/util/NoOpCacheManager.java]: Will do
